// weather_widget.dart

import 'package:flutter/material.dart';
import 'package:weather/api/conclusion.dart';

class WeatherWidget extends StatelessWidget {
  final Autogenerated? response;

  const WeatherWidget({Key? key, this.response}) : super(key: key);

  @override
  Widget build(BuildContext context) {
    if (response == null) {
      return Text("No weather data available");
    }

    var currentWeather = response?.current;
    if (currentWeather == null) {
      return Text("No current weather data available");
    } else {
      return Column(
        crossAxisAlignment: CrossAxisAlignment.start,
        children: [
          Row(
            crossAxisAlignment: CrossAxisAlignment.end,
            children: [
              const Icon(
                Icons.location_on,
                size: 50,
              ),
              Text(
                response?.location?.name ?? "",
                style: TextStyle(
                  fontSize: 40,
                  fontWeight: FontWeight.w300,
                ),
              ),
              Text(
                response?.location?.country ?? "",
                style: TextStyle(
                  fontSize: 20,
                  fontWeight: FontWeight.w300,
                ),
              )
            ],
          ),
          const SizedBox(height: 10),
          Row(
            crossAxisAlignment: CrossAxisAlignment.end,
            children: [
              Padding(
                padding: const EdgeInsets.all(8.0),
                child: Text(
                  (response?.current?.tempC.toString() ?? "") + " °c",
                  style: TextStyle(
                    fontSize: 55,
                    fontWeight: FontWeight.bold,
                  ),
                ),
              ),
            ],
          ),
          Text(
            (response?.current?.condition?.text.toString() ?? ""),
            style: TextStyle(
              fontSize: 20,
              fontWeight: FontWeight.w500,
            ),
          ),
          Center(
            child: SizedBox(
              child: Image.network("https:${response?.current?.condition?.icon}".replaceAll("64x64", "128x128"),
                scale: 0.7,
              ),
            ),
          ),
          Card(
            elevation: 4,
            color: Colors.white,
            child: Column(
              children: [
                Row(
                  mainAxisAlignment: MainAxisAlignment.spaceAround,
                  children: [
                    _dataAndTitleWidget("Humidity", response?.current?.humidity?.toString() ?? ""),
                    _dataAndTitleWidget("Wind Speed",  "${response?.current?.windKph?.toString() ?? ""} km/h"),
                  ],
                ),
                Row(
                  mainAxisAlignment: MainAxisAlignment.spaceAround,
                  children: [
                    _dataAndTitleWidget("UV", response?.current?.uv?.toString() ?? ""),
                    _dataAndTitleWidget("Percipitation",  "${response?.current?.precipMm?.toString() ?? ""} mm"),
                  ],
                ),
                Row(
                  mainAxisAlignment: MainAxisAlignment.spaceAround,
                  children: [
                    _dataAndTitleWidget("Local Time", response?.location?.localtime?.split(" ").last ?? ""),
                    _dataAndTitleWidget("Local Data",  response?.location?.localtime?.split(" ").first ?? ""),
                  ],
                )
              ],
            ),
          )
        ],
      );
    }
  }

  Widget _dataAndTitleWidget(String title, String data) {
    return Padding(
      padding: const EdgeInsets.all(17.0),
      child: Column(
        children: [
          Text(data, style: const TextStyle(
              fontSize: 27,
              color: Colors.black87,
              fontWeight: FontWeight.w600
          ),),
          Text(title, style: const TextStyle(
              color: Colors.black87,
              fontWeight: FontWeight.w600
          ),),
        ],
      ),
    );
  }
}